# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NZ-GW-workshop CBC Tutorial
author: Avi Vajpeyi

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: ''

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
